apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mybox
  name: mybox
spec:
  containers:
  - args:
    - sh
    - -c
    - for variable in 1 2 3 4 5; do echo $(DB_PASSWORD);sleep 15; done; sleep 120;
    envFrom:
    - configMapRef:
       name: rivers
    env:
    - name: DB_PASSWORD
      valueFrom:
          secretKeyRef:
                  name: db
                  key: DB_PASSWORD
    - name: time
      value: "10"
    image: busybox
    name: mybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
