apiVersion: v1
data:
  DB_PASSWORD: d2hhdGlzaXQ=
  DB_USER: cm9vdA==
kind: Secret
metadata:
  name: dbdetails
#k create secret generic dbdetails --from-literal=DB_USER=root --from-literal=DB_PASSWORD=whatisit --dry-run -o yaml > dbdetails-secret.yaml
