apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mybox
  name: mybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybox
  strategy: {}
  template:
    metadata:
      labels:
        app: mybox
    spec:
      containers:
      - image: adityapratapbhuyan/k8s-docker-config:1.0
        name: k8s-docker-config
        envFrom:
        - configMapRef:
            name: games
        - configMapRef:
            name: ui
        env:
        - name: ENGLISH
          valueFrom:
           configMapKeyRef:
            name: languages
            key: ENGLISH 
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbdetails
              key: DB_PASSWORD
        - name: ASIA
          value: BHUTAN
        resources: {}
status: {}
