apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mybox
  name: mybox
spec:
  containers:
  - env:
    - name: ASIA
      value: INDIA
    - name: SOUTH_AMERICA
      value: AMAZON
    - name: DB_PASSWORD
      value: whatisthat
    image: adityapratapbhuyan/k8s-docker-config:1.0
    name: mybox
 
