apiVersion: v1
data:
  ASIA: NILE
  NORTH_AMERICA: MISSISIPI
kind: ConfigMap
metadata:
  name: rivers
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mybox
  name: mybox
spec:
  volumes:
  - name: config-volume
    configMap:
     name: rivers
  containers:
  - command: [ "/bin/sh", "-c", "for variable in 1 2 3 4 5; do cat  /etc/config/ASIA;sleep 15;done;  sleep 300;" ]
    image: busybox
    name: mybox
    volumeMounts:
    - name: config-volume
      mountPath: "/etc/config"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}