#k run --image=busybox --restart=Never mybox --env=time=10 sh --dry-run -o yaml   --  -c 'echo $(time)'
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mybox
  name: mybox
spec:
  containers:
  - command: [ "/bin/sh", "-c", 'echo "${workshop}"; sleep 10' ]
    imagePullPolicy: IfNotPresent
    env:
    - name: workshop
      value: kubernetes
    - name: duration
      value: 5days
    image: busybox
    name: mybox
