apiVersion: v1
data:
  ASIA: NILE
  NORTH_AMERICA: MISSISIPI
kind: ConfigMap
metadata:
  name: rivers
---
apiVersion: v1
data:
  ASIA: INDIA
  AUSTRALIA: AUSTRALIA
  EUROPE: RUSSIA
kind: ConfigMap
metadata:
  name: countries
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mybox
  name: mybox
spec:
  containers:
  - command: [ "/bin/sh", "-c", "env; sleep 120" ]
    image: busybox
    name: mybox
    envFrom:
    - configMapRef:
       name: rivers
    - configMapRef:
       name: countries
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}