apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - command:
    - sh
    - -c
    - echo Hello; echo "$(workshop) ";sleep 200
    image: busybox
    env:
    - name: workshop
      value: Kubernetes
    - name: duration
      value: 5days
    imagePullPolicy: IfNotPresent
    name: busybox

