apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pages
  name: pages
spec:
  containers:
  - image: dellcloud/pages:1.0
    name: pages
    imagePullPolicy: IfNotPresent
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 10
