apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /var/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
spec:
  volumes:
    - name: dev-volume
      persistentVolumeClaim:
        claimName: dev-claim
  containers:
    - name: dev-container
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: dev-volume