apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-storage-pod
spec:
  volumes:
    - name: dev-volume
      persistentVolumeClaim:
        claimName: storage-claim
  containers:
    - name: dev-storage-container
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: dev-volume