apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dev
  namespace: dev
spec:
  storageClassName: database-dev
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi