apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-without-ttl
spec:
  jobTemplate:
    metadata:
      name: cronjob
    spec:
      template:
        metadata:
        spec:
          volumes:
            - name: tz-config
              hostPath:
                path: /usr/share/zoneinfo/Europe/Moscow
          containers:
          - image: busybox
            name: cronjob
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh"]
            args: ["-c","echo Time: 3.30 pm. It is break time. Lets stretch out a bit or have a coffee!"]
            volumeMounts:
              - name: tz-config
                mountPath: /etc/localtime
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
